Init declarative cosmetic rules proposal
maximtop/webextensions pull request #1
Opened 2023-02-16 15:01 UTC by maximtop

2023-02-20 15:54 UTC, ameshkov requested changes

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +Cosmetic rules can be divided into three groups: Hiding Rules, CSS Rules, and Scriptlets.
Обычно их называют Element hiding rules

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +Hiding rules can be used to hide various elements on web pages, such as advertisements, pop-ups, banners, and other unwanted content. By defining the CSS selectors of these elements, users can hide t
Давай списки как списки форматировать - читать удобнее. Также думаю будет корректнее описать техническую суть правил, а не только то, зачем мы их используем.

* Element hiding rules: basically, inject a CSS `display: none` style to the page.
* CSS rules: inject a custom CSS style to the page. There are some limitations to what styles can be injected, i.e. you cannot use a style that loads any additional resource. For example, `url()`, etc.
* Scriptlets: modify the page behavior by executing a small named JS function that comes with the extension. Example: `abort-property-read(propName)`.

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +The extension needs to inject scripts and styles as early as possible for a smoother user experience (e.g. blinking DOM elements). It also needs to patch scripts before websites can copy DOM API meth
Не объясняется какое конкретно API используется. Фокусируешься только на том, что надо как можно раньше вставить стили. Также из объяснения непонятно, почему просто из контент скрипта нельзя вставить стили в самом начале загрузки страницы.

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +Extensions built on top of MV3 can use the same sophisticated way to inject styles and scripts, but they lack the guarantee that the engine will start. This is because event-driven background pages o
Не думаю что прям есть смысл на этом фокусироваться, вроде как исправили же.

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +Hiding rules are one of the most popular rule types - for example, AdGuard's basic filter contains 98500 rules, 24800 of which are hiding rules.
basic filter это Base filter?

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +Scriptlet rules make up 3000 rules and cosmetic CSS rules make up 1500 rules.
3000 и 1500 вообще всего или в базовом фильтре?

2023-02-20 15:54 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +We need to be able to apply cosmetic rules before the page loads, without having to use content scripts and complicated logic. We also do not want to lose any current features.
Главная цель не только и не столько в том, чтобы применять правила до загрузки страницы. Я вообще в ношне описывал в чем цель.

2023-02-21 14:11 UTC, maximtop commented on proposals/declarative-cosmetic.md
> +Scriptlet rules make up 3000 rules and cosmetic CSS rules make up 1500 rules.
в базовом

2023-02-21 14:25 UTC, maximtop commented
@ameshkov постарался пофиксить твои замечания

2023-03-15 12:13 UTC, ameshkov requested changes

2023-03-15 12:13 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +
```
### Issues

* Content blocking extensions require wide permissions mostly in order to apply cosmetic rules.
* Timing. Content blocking extensions would like to apply cosmetic rules as soon as possible, i.e. before the page has been loaded and page scripts start running. With the current approach there's a short delay blah blah blah

```

2023-03-15 12:13 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +### Declarative element hiding rules
Стоит написать, что это типа пример как могут выглядеть косметик правила.

Его можно и нужно расширить, но перед этим хотелось бы получить фидбэк на общую идею.

2023-03-15 15:43 UTC, ameshkov requested changes

2023-03-15 15:43 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +* Content blocking extensions require wide permissions, mostly to apply cosmetic rules. This is not secure and may scare some people that the extension may be watching them.
Я б не стал писать про "not secure", просто если этого можно будет избежать то почему нет.

2023-03-15 15:43 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +## Several examples of how it can be used
Мы все-таки не примеры использования даем, а пример того, как могло бы выглядеть API.

2023-03-15 15:43 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +type RuleActionType = 'hide' | 'allow' | 'css' | 'revert_css' | 'scriptlet';
`allow` и `revert_css` выглядит странно, я бы тут не приводил.

Вообще можно написать что-то типа `hide | css | scriptlet | ....` чтоб подчеркнуть что экшны можно расширить

2023-03-15 15:43 UTC, ameshkov commented on proposals/declarative-cosmetic.md
> +const elemHideRule: Rule = {
Думаю не надо пытаться покрыть все типы правил сейчас, можно одно типа `hide` показать да и все.

Также примеры конкретных правил должны быть отделены от API.

2023-03-16 06:33 UTC, 105th approved these changes

2023-03-16 06:33 UTC, merged